import java.lang.management.ManagementFactory

plugins {
    // alias 就是 id xxx version xxx 的简写形式
    // 同一个 plugins{} 块中声明的插件会被顺序添加到同一个的类加载器中，所以这里的插件能够互相访问各自定义的类。
    // 有一个例外，就是 buildSrc 中的插件，它会在更高级别类加载器中加载，因此我们在各个构建脚本中使用 buildSrc 中定义的类(除了 settings.gradle)。
    id("me.liwenkun.readme-process")
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin) apply false
    alias(libs.plugins.kapt) apply false
}

println "-------------- root project classloader hierarchy start -----------------"
ClassLoader classLoader = this.class.classLoader;
while (classLoader != null) {
    println classLoader
    classLoader = classLoader.parent
}
println "-------------- root project classloader hierarchy end -----------------"

//https://discuss.gradle.org/t/depending-on-types-of-a-3rd-party-plugin-in-buildsrc/49453
tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

tasks.register('testTask') {
    doLast {
        def runtime = ManagementFactory.getRuntimeMXBean()
        def name = runtime.name
        def pid = name.substring(0, name.indexOf("@")).toLong()
        println("gradle 任务 所在进程 Pid: $pid")
        println("gradle 任务 vm 版本: ${System.getProperty("java.version")}")
    }
}

def runtime = ManagementFactory.getRuntimeMXBean()
def name = runtime.name
def pid = name.substring(0, name.indexOf("@")).toLong()
println("gradle 所在进程 Pid: $pid")
println("gradle vm 版本: ${System.getProperty("java.version")}")

MyPlugin {
    outputFile = layout.buildDirectory.file("M_README.md")
}